name: Shortify
main: com.nullblock.vemacs.Shortify.platforms.bukkit.Shortify
version: 1.6.0
description: The most advanced URL shortener for Bukkit, Spout, and Forge. A fast and configurable plugin that automatically uses goo.gl, bit.ly, TinyURL, turl.ca (experimental) or is.gd to shorten all detected URLs in a player message.
author: vemacs
authors:
- tuxed/minecrafter
- Racorac
website: http://dev.bukkit.org/server-mods/shortify/
permissions:
    shortify.*:
        description: Allows the use of all Shortify functions
        children:
            shortify.shorten.*: true
            shortify.admin: true
    shortify.shorten.*:
        description: Allows the shortening of all URLs
        children:
            shortify.shorten.cmd: true
            shortify.shorten: true
    shortify.shorten:
        description: Allows you to shorten a URL
        default: true
    shortify.admin:
        description: Allows you to reload Shortify
        default: op
    shortify.shorten.cmd:
        description: Shortens URLs in all commands
        default: true
commands:
    shortify:
        description: Shortify administration command
